### ISSUE TITLE
Gradients

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/zepcode#1]
Add Swift code snippet for gradients:
<p align="center">
<img src="https://user-images.githubusercontent.com/5051597/36596905-82f82fa4-18d1-11e8-8d2e-9f006b35e43c.png"/>
</p>
Don’t forget about angular and radial gradients.

**Comment by ignatovSA** [comment]
Beware while using `CAGradientLayer`, this may lead to results that differ from Zeplin mockups.

The problem is described:

**Comment by artemnovichkov** [comment]
Thanks a lot, @ignatovSA! I have read the article on Medium and know about this problem. That's why the feature still in WIP status. Your example looks clear and laconic. Do you want to send a PR? It would be great!
