### ISSUE TITLE
Saving color palette doesn't work

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/zepcode#16]
### Version of Zepcode:
0.5.0
### Generated snippet:
```swift
import UIKit

extension UIColor {

    convenience init(r red: Int, g green: Int, b blue: Int, a: CGFloat = 1) {
        self.init(red: CGFloat(red) / 255, green: CGFloat(green) / 255, blue: CGFloat(blue) / 255, alpha: a)
    }

    static let dodgerBlue = UIColor(red: 72/255, green: 171/255, blue: 255/255, alpha: 1)
    
}
```
### What's wrong:
Can't save snippet into file.

**Comment by dirtybit** [comment]
It crashes since the second argument of `generateColorExtension` is missing here:
https://github.com/artemnovichkov/zepcode/blob/6eecca3a4e1fc3135d171b2e760eadde9073bf3a/src/index.js#L103-L105

I guess `options(context)` is also required for this function to run properly.

**Comment by artemnovichkov** [comment]
@dirtybit, you're right! Thank you!
