### ISSUE TITLE
Attributed strings

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/zepcode#2]
I don't like the style of the code from default `Attributed Strings` extension:
```swift
let attributedString = NSMutableAttributedString(string: "Anastasiya K. \n& Constance", attributes: [
  .font: UIFont(name: "BloggerSans-Bold", size: 18.0)!,
  .foregroundColor: UIColor(white: 0.0, alpha: 1.0)
])
attributedString.addAttribute(.foregroundColor, value: UIColor.barbiePink, range: NSRange(location: 15, length: 1))
```
It uses ranges. I want to use `append` method of `NSMutableAttributedString` and different strings.

**Comment by ignatovSA** [comment]
Possible approach - using some kind of styles.  

You can check [this gist](https://gist.github.com/ignatovSA/d7978e748b7a0e57201ffa479f98afa3) for the sample. It's inspired by [stylesync](https://github.com/dylanslewis/stylesync) tool.

**Comment by artemnovichkov** [comment]
@ignatovSA looks good! I'll keep in mind this approach.

**Comment by artemnovichkov** [comment]
We decided to implement it as a separate extension - [Stylin](https://github.com/artemnovichkov/stylin).
